In [ ]:
%pip install transformers datasets torch accelerate evaluate peft trl

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.8.0+cu126)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.10.1)
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.17.1)
Collecting trl
  Downloading trl-0.23.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.35.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.1.10)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.10.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 2.4 MB/s eta 0:00:00
Downloading trl-0.23.1-py3-none-any.whl (564 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 564.6/564.6 kB 11.8 MB/s eta 0:00:00
Installing collected packages: trl, evaluate
Successfully installed evaluate-0.4.6 trl-0.23.1

In [ ]:
from transformers import DistilBertTokenizer, DistilBertForSequenceClassification
import torch

In [ ]:
model_name="distilbert/distilbert-base-uncased"
tokenizer=DistilBertTokenizer.from_pretrained(model_name)
model=DistilBertForSequenceClassification.from_pretrained(model_name,num_labels=3)

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert/distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
inputs=["This product exceeded all my expectations and works perfectly!",
"The battery life is amazing, and the phone feels great in my hand.",
"I'm so happy with their customer service—they solved my issue quickly.",
"The food was absolutely delicious; I would highly recommend this restaurant.",
"The item broke after one use, and the support team was completely unhelpful.",
"I am amazed by the speed of the processor but disappointed that it heats up quickly.",
"This was the worst movie I've ever seen. What a terrible waste of money.",
"The delivery was late, and the package arrived damaged."]

In [ ]:
def tokenize(example):
  # Process the batch of texts in the 'English' column
  return tokenizer(example['English'], truncation=True, max_length=100, padding='max_length', padding_side='left', return_tensors="pt")

In [ ]:
from datasets import load_dataset,Dataset
import pandas as pd

In [ ]:
data=load_dataset('leduckhai/Sentiment-Reasoning')

In [ ]:
training_dataset=data['train'].remove_columns([col for col in data['train'].column_names if col not in ['English', 'label']])
validation_dataset=data['test'].remove_columns([col for col in data['test'].column_names if col not in ['English', 'label']])

In [ ]:
from transformers import Trainer, TrainingArguments
import evaluate

In [ ]:
# training
labels={'neutral':0,'positive':1,'negative':2}
tokenize_datasets=training_dataset.map(tokenize,batched=True,remove_columns=['English'])
tokenize_datasets=tokenize_datasets.map(lambda example: {'label': labels[example['label']]})
tokenize_datasets=tokenize_datasets.rename_column('label','labels')
tokenize_datasets.set_format("torch")

# val
tokenize_validation_dataset = validation_dataset.map(tokenize, batched=True, remove_columns=['English'])
tokenize_validation_dataset=tokenize_validation_dataset.map(lambda example: {'label': labels[example['label']]})
tokenize_validation_dataset=tokenize_validation_dataset.rename_column('label','labels')
tokenize_validation_dataset.set_format("torch")

In [ ]:
tokenize_datasets

Dataset({
    features: ['labels', 'input_ids', 'attention_mask'],
    num_rows: 5612
})

In [ ]:
accuracy=evaluate.load('accuracy')
f1=evaluate.load('f1')

def compute_metrice(eval_metrice):
  logits,labels=eval_metrice
  predictions=torch.argmax(torch.from_numpy(logits),dim=-1)
  acc = accuracy.compute(predictions=predictions, references=labels)['accuracy']
  f1_score = f1.compute(predictions=predictions, references=labels, average='weighted')['f1']
  return {"accuracy": acc, "f1": f1_score}

In [ ]:
training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=10,
    per_device_train_batch_size=64,
    per_device_eval_batch_size=64,
    learning_rate=2e-4,
    eval_strategy="epoch",  # Evaluate at the end of each epoch
    save_strategy="epoch",        # Save checkpoints at the end of each epoch
    load_best_model_at_end=True,  # Load the best model at the end of training
    metric_for_best_model="f1"
)

trainer = Trainer(
    model=model.to('cuda'),
    args=training_args,
    train_dataset=tokenize_datasets,  # Assumes pre-processed dataset
    eval_dataset=tokenize_validation_dataset,    # Assumes pre-processed dataset
    compute_metrics=compute_metrice, # Function to compute metrics
)

In [ ]:
trainer.train()

wandb: Currently logged in as: medicalassistance-ai (medicalassistance-ai-maai) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

TrainOutput(global_step=880, training_loss=0.16887943907217545, metrics={'train_runtime': 700.8918, 'train_samples_per_second': 80.069, 'train_steps_per_second': 1.256, 'total_flos': 1451992771224000.0, 'train_loss': 0.16887943907217545, 'epoch': 10.0})

In [ ]:
lil_input=[]
for inp in inputs:
  tokens=tokenizer(inp, truncation=True, max_length=100, padding='max_length', padding_side='left', return_tensors="pt").to('cuda')
  print(tokens)
  lil_input.append(tokens)

{'input_ids': tensor([[    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,   101,  2023,
          4031, 14872,  2035,  2026, 10908,  1998,  2573,  6669,   999,   102]],
       device='cuda:0'), 'attention_mask': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1]], device='cuda:0')}
{'input_ids': tensor([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  101,
         1996, 6046, 2166, 2003, 6429, 1010, 1998, 1996, 3042, 5683, 2307, 1999,
         2026, 2192, 1012,  102]], device='cuda:0'), 'attention_mask': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1]], device='cuda:0')}
{'input_ids': tensor([[    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,   101,  1045,  1005,  1049,  2061,  3407,  2007,  2037,
          8013,  2326,  1517,  2027, 13332,  2026,  3277,  2855,  1012,   102]],
       device='cuda:0'), 'attention_mask': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1]], device='cuda:0')}
{'input_ids': tensor([[    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,   101,  1996,  2833,  2001,  7078,
         12090,  1025,  1045,  2052,  3811, 16755,  2023,  4825,  1012,   102]],
       device='cuda:0'), 'attention_mask': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1]], device='cuda:0')}
{'input_ids': tensor([[    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
           101,  1996,  8875,  3631,  2044,  2028,  2224,  1010,  1998,  1996,
          2490,  2136,  2001,  3294,  4895, 16001, 14376,  5313,  1012,   102]],
       device='cuda:0'), 'attention_mask': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1]], device='cuda:0')}
{'input_ids': tensor([[    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,   101,  1045,  2572, 15261,  2011,  1996,  3177,  1997,  1996,
         13151,  2021,  9364,  2008,  2009, 18559,  2039,  2855,  1012,   102]],
       device='cuda:0'), 'attention_mask': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1]], device='cuda:0')}
{'input_ids': tensor([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,  101, 2023, 2001, 1996,
         5409, 3185, 1045, 1005, 2310, 2412, 2464, 1012, 2054, 1037, 6659, 5949,
         1997, 2769, 1012,  102]], device='cuda:0'), 'attention_mask': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1]], device='cuda:0')}
{'input_ids': tensor([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,  101, 1996, 6959, 2001, 2397, 1010, 1998, 1996, 7427,
         3369, 5591, 1012,  102]], device='cuda:0'), 'attention_mask': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1]], device='cuda:0')}

In [ ]:
for out in lil_input:
  with torch.no_grad():
    output = model(**out)
    # Get the predicted class index from the logits
    predicted_class_index = torch.argmax(output.logits, dim=-1)
    print(f"-> Predicted class index: {predicted_class_index.item()}")

-> Predicted class index: 1
-> Predicted class index: 1
-> Predicted class index: 1
-> Predicted class index: 1
-> Predicted class index: 2
-> Predicted class index: 2
-> Predicted class index: 2
-> Predicted class index: 2

## Lets try peft now

In [ ]:
from peft import LoraConfig,get_peft_model,TaskType,prepare_model_for_kbit_training
from trl import SFTTrainer

In [ ]:
model.config.use_cache=False

In [ ]:
model=prepare_model_for_kbit_training(model)

In [ ]:
Loraconfig=LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=['q_lin','v_lin'],
    lora_dropout=0.05,
    bias='none',
    task_type=TaskType.SEQ_CLS
)

In [ ]:
peft_model=get_peft_model(model,Loraconfig)

In [ ]:
peft_model.print_trainable_parameters()

trainable params: 887,811 || all params: 67,843,590 || trainable%: 1.3086

In [ ]:
training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=10,
    per_device_train_batch_size=64,
    per_device_eval_batch_size=64,
    learning_rate=2e-4,
    eval_strategy="epoch",  # Evaluate at the end of each epoch
    save_strategy="epoch",        # Save checkpoints at the end of each epoch
    load_best_model_at_end=True,  # Load the best model at the end of training
    metric_for_best_model="f1"
)

trainer = Trainer(
    model=peft_model.to('cuda'),
    args=training_args,
    train_dataset=tokenize_datasets,  # Assumes pre-processed dataset
    eval_dataset=tokenize_validation_dataset,    # Assumes pre-processed dataset
    compute_metrics=compute_metrice, # Function to compute metrics
)

In [ ]:
trainer.train()

wandb: Currently logged in as: medicalassistance-ai (medicalassistance-ai-maai) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

TrainOutput(global_step=880, training_loss=0.5181391629305753, metrics={'train_runtime': 384.679, 'train_samples_per_second': 145.888, 'train_steps_per_second': 2.288, 'total_flos': 1481887143216000.0, 'train_loss': 0.5181391629305753, 'epoch': 10.0})

In [ ]:
lil_input=[]
#tokenizer.pad_token = tokenizer.eos_token
for inp in inputs:
  tokens=tokenizer(inp, truncation=True, max_length=100, padding='max_length', padding_side='left', return_tensors="pt").to('cuda')
  print(tokens)
  lil_input.append(tokens)

{'input_ids': tensor([[    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,   101,  2023,
          4031, 14872,  2035,  2026, 10908,  1998,  2573,  6669,   999,   102]],
       device='cuda:0'), 'attention_mask': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1]], device='cuda:0')}
{'input_ids': tensor([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  101,
         1996, 6046, 2166, 2003, 6429, 1010, 1998, 1996, 3042, 5683, 2307, 1999,
         2026, 2192, 1012,  102]], device='cuda:0'), 'attention_mask': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1]], device='cuda:0')}
{'input_ids': tensor([[    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,   101,  1045,  1005,  1049,  2061,  3407,  2007,  2037,
          8013,  2326,  1517,  2027, 13332,  2026,  3277,  2855,  1012,   102]],
       device='cuda:0'), 'attention_mask': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1]], device='cuda:0')}
{'input_ids': tensor([[    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,   101,  1996,  2833,  2001,  7078,
         12090,  1025,  1045,  2052,  3811, 16755,  2023,  4825,  1012,   102]],
       device='cuda:0'), 'attention_mask': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1]], device='cuda:0')}
{'input_ids': tensor([[    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
           101,  1996,  8875,  3631,  2044,  2028,  2224,  1010,  1998,  1996,
          2490,  2136,  2001,  3294,  4895, 16001, 14376,  5313,  1012,   102]],
       device='cuda:0'), 'attention_mask': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1]], device='cuda:0')}
{'input_ids': tensor([[    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,   101,  1045,  2572, 15261,  2011,  1996,  3177,  1997,  1996,
         13151,  2021,  9364,  2008,  2009, 18559,  2039,  2855,  1012,   102]],
       device='cuda:0'), 'attention_mask': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1]], device='cuda:0')}
{'input_ids': tensor([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,  101, 2023, 2001, 1996,
         5409, 3185, 1045, 1005, 2310, 2412, 2464, 1012, 2054, 1037, 6659, 5949,
         1997, 2769, 1012,  102]], device='cuda:0'), 'attention_mask': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1]], device='cuda:0')}
{'input_ids': tensor([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,  101, 1996, 6959, 2001, 2397, 1010, 1998, 1996, 7427,
         3369, 5591, 1012,  102]], device='cuda:0'), 'attention_mask': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1]], device='cuda:0')}

In [ ]:
for out in lil_input:
  with torch.no_grad():
    output = model(**out)
    # Get the predicted class index from the logits
    predicted_class_index = torch.argmax(output.logits, dim=-1)
    print(f"-> Predicted class index: {predicted_class_index.item()}")

-> Predicted class index: 1
-> Predicted class index: 1
-> Predicted class index: 1
-> Predicted class index: 1
-> Predicted class index: 2
-> Predicted class index: 0
-> Predicted class index: 2
-> Predicted class index: 2

as you can see even thoough performence have reduced but training time has halfed

## Project 2: Domain-Specific Summarization

In [ ]:
!pip install -U bitsandbytes

Collecting bitsandbytes
  Downloading bitsandbytes-0.48.1-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.8.0+cu126)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (25.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Downloading bitsandbytes-0.48.1-py3-none-manylinux_2_24_x86_64.whl (60.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.1/60.1 MB 15.9 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.48.1

In [ ]:
import torch
from datasets import load_dataset
from trl import SFTTrainer,SFTConfig
from peft import LoraConfig,get_peft_model,prepare_model_for_kbit_training
from transformers import AutoModelForSeq2SeqLM,AutoTokenizer,BitsAndBytesConfig,TextStreamer
import evaluate

In [ ]:
dataset=load_dataset('ccdv/pubmed-summarization')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

section/train-00000-of-00005.parquet:   0%|          | 0.00/210M [00:00<?, ?B/s]

section/train-00001-of-00005.parquet:   0%|          | 0.00/208M [00:00<?, ?B/s]

section/train-00002-of-00005.parquet:   0%|          | 0.00/207M [00:00<?, ?B/s]

section/train-00003-of-00005.parquet:   0%|          | 0.00/211M [00:00<?, ?B/s]

section/train-00004-of-00005.parquet:   0%|          | 0.00/210M [00:00<?, ?B/s]

section/validation-00000-of-00001.parque(…):   0%|          | 0.00/59.0M [00:00<?, ?B/s]

section/test-00000-of-00001.parquet:   0%|          | 0.00/58.9M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/119924 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/6633 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/6658 [00:00<?, ? examples/s]

In [ ]:
# Split the 'train' split of the dataset
dataset1 = dataset['train'].train_test_split(test_size=0.1)

In [ ]:
model_name='facebook/bart-large-cnn'
tokenize=AutoTokenizer.from_pretrained(model_name)
model=AutoModelForSeq2SeqLM.from_pretrained(model_name,device_map='auto')

config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

In [ ]:
dataset

DatasetDict({
    train: Dataset({
        features: ['article', 'abstract'],
        num_rows: 119924
    })
    validation: Dataset({
        features: ['article', 'abstract'],
        num_rows: 6633
    })
    test: Dataset({
        features: ['article', 'abstract'],
        num_rows: 6658
    })
})

In [ ]:
dataset1

DatasetDict({
    train: Dataset({
        features: ['article', 'abstract'],
        num_rows: 107931
    })
    test: Dataset({
        features: ['article', 'abstract'],
        num_rows: 11993
    })
})

In [ ]:
x=dataset['train']['abstract']

In [ ]:
x

Column(["background : the present study was carried out to assess the effects of community nutrition intervention based on advocacy approach on malnutrition status among school - aged children in shiraz , iran.materials and methods : this case - control nutritional intervention has been done between 2008 and 2009 on 2897 primary and secondary school boys and girls ( 7 - 13 years old ) based on advocacy approach in shiraz , iran . \n the project provided nutritious snacks in public schools over a 2-year period along with advocacy oriented actions in order to implement and promote nutritional intervention . for evaluation of effectiveness of the intervention growth monitoring indices of pre- and post - intervention were statistically compared.results:the frequency of subjects with body mass index lower than 5% decreased significantly after intervention among girls ( p = 0.02 ) . \n however , there were no significant changes among boys or total population . \n the mean of all anthropometric indices changed significantly after intervention both among girls and boys as well as in total population . \n the pre- and post - test education assessment in both groups showed that the student 's average knowledge score has been significantly increased from 12.5  3.2 to 16.8  4.3 ( p < 0.0001).conclusion : this study demonstrates the potential success and scalability of school feeding programs in iran . \n community nutrition intervention based on the advocacy process model is effective on reducing the prevalence of underweight specifically among female school aged children .", 'backgroundanemia in patients with cancer who are undergoing active therapy is commonly encountered and may worsen quality of life in these patients . the effect of blood transfusion is often temporary and may be associated with serious adverse events . \n erythropoiesis - stimulating agents are not effective in 30%50% of patients and may have a negative effect on overall survival.aimsto assess the efficacy and feasibility of intravenous iron therapy in patients with cancer who have non - iron - deficiency anemia and who are undergoing treatment with chemotherapy without the use of erythropoiesis - stimulating agents.methodsadult patients with solid cancers and non - iron - deficiency anemia were included . \n ferric sucrose at a dose of 200 mg was given in short intravenous infusions weekly for a total of 12 weeks . \n hemoglobin level was measured at baseline , every 3 weeks , and 2 weeks after the last iron infusion ( week 14 ) . \n adverse events related to intravenous iron were prospectively reported.resultsof 25 patients included , 19 ( 76.0% ) completed at least three iron infusions and 14 ( 56.0% ) finished the planned 12 weeks of therapy . \n the mean hemoglobin level of the 25 patients at baseline was 9.6 g / dl ( median , 9.9 g / dl ; range , 6.9 g / dl 10.9 g / dl ) . the mean change in hemoglobin level for the 15 patients who completed at least 9 treatments was 1.7 g / dl ( median , 1.1 g / dl ; range , 1.9 g / dl to 3.2 g / dl ) ; it reached 2.1 g / dl ( median , 1.3 g / dl ; range , 0.2 g / dl to 4.6 g / dl ; p = 0.0007 ) for the 14 patients who completed all 12 weekly treatments . \n five ( 20.0% ) patients were transfused and considered as treatment failures . \n no treatment - related adverse events were reported.conclusionintravenous iron treatment alone is safe and may reduce blood transfusion requirements and improve hemoglobin level in patients with cancer who are undergoing anticancer therapy . \n further randomized studies are needed to confirm these findings .', 'tardive dystonia ( td ) is a serious side effect of antipsychotic medications , more with typical antipsychotics , that is potentially irreversible in affected patients . \n studies show that newer atypical antipsychotics have a lower risk of td . as a result , many clinicians may have developed a false sense of security when prescribing these medications . \n we report a case of 20-year - old male with hyperthymic temperament and borderline intellectual functioning , who developed severe td after low dose short duration exposure to atypical antipsychotic risperidone and then olanzapine . \n the goal of this paper is to alert the reader to be judicious and cautious before using casual low dose second generation antipsychotics in patient with no core psychotic features , hyperthymic temperament , or borderline intellectual functioning suggestive of organic brain damage , who are more prone to develop adverse effects such as td and monitor the onset of td in patients taking atypical antipsychotics .', 'many lepidopteran insects are agricultural pests that affect stored grains , food and fiber crops . \n these insects have negative ecological and economic impacts since they lower crop yield , and pesticides are expensive and can have off - target effects on beneficial arthropods \n . a better understanding of lepidopteran immunity will aid in identifying new targets for the development of specific insect pest management compounds . \n a fundamental aspect of immunity , and therefore a logical target for control , is the induction of antimicrobial peptide ( amp ) expression . \n these peptides insert into and disrupt microbial membranes , thereby promoting pathogen clearance and insect survival . \n pathways leading to amp expression have been extensively studied in the dipteran drosophila melanogaster . however , diptera are an important group of pollinators and pest management strategies that target their immune systems is not recommended . \n recent advances have facilitated investigation of lepidopteran immunity , revealing both conserved and derived characteristics . \n although the general pathways leading to amp expression are conserved , specific components of these pathways , such as recognition proteins have diverged . in this review \n we highlight how such comparative immunology could aid in developing pest management strategies that are specific to agricultural insect pests .', "we present an unusual case of recurrent cough syncope in a 43-year - old woman , which was initially thought to be seizures . \n syncopal episodes were triggered by paroxysms of cough and were characterized by unresponsiveness and myoclonic jerks in her extremities . \n she had a left - sided glomus jugulare tumor that extended into the posterior cranial fossa with evidence of worsening communicating hydrocephalus on brain imaging . \n we postulate that bouts of cough produced increased intracranial pressure both by raising intrathoracic and intraabdominal pressures as well as by transient obstruction to cerebrospinal fluid flow secondary to intermittent tonsillar herniation during cough . \n this resulted in diffuse decrease in cerebral blood flow causing syncope . \n the patient 's syncopal episodes decreased in frequency once an external ventricular drain was placed followed by a ventriculoperitoneal shunt . \n search for factors that can increase intracranial pressure seems warranted in patients with recurrent cough syncope ."])

In [ ]:
def tokenizer(example):
  return tokenize(example['text'],max_length=1024,truncation=True,padding_side='left',padding='max_length',return_tensors='pt')

In [ ]:
def text_gen(example):
  example['text']=f"Summarize this medical abstract: {example['article']}\nSummary: {example['abstract']}"
  return example

In [ ]:
data=dataset1.map(text_gen)

NameError: name 'dataset1' is not defined

In [ ]:
data

Dataset({
    features: ['article', 'abstract', 'text'],
    num_rows: 107931
})

In [ ]:
tokenized_train=data.map(tokenizer,batched=True,remove_columns=["article", "abstract", "text"])

Map:   0%|          | 0/107931 [00:00<?, ? examples/s]

In [ ]:
tokenized_train

Dataset({
    features: ['input_ids', 'attention_mask'],
    num_rows: 107931
})

In [ ]:
print(tokenized_train[0])

{'input_ids': [0, 38182, 3916, 2072, 42, 1131, 20372, 35, 11, 189, 11735, 2156, 5, 474, 575, 5200, 942, 36, 1368, 19911, 102, 4839, 1027, 10, 2570, 7, 14518, 812, 111, 1330, 1042, 88, 5, 26467, 1322, 12429, 3207, 467, 36, 752, 5124, 2156, 11735, 102, 4839, 479, 1437, 50118, 1165, 11, 5, 2570, 21, 41, 1965, 7, 9160, 5, 1850, 4460, 812, 36, 1663, 701, 4839, 22507, 467, 13, 4566, 18381, 21875, 11, 5, 701, 9, 1098, 1663, 479, 1437, 50118, 1368, 19911, 102, 128, 29, 2570, 21, 45, 6264, 142, 2156, 19, 5, 32442, 27587, 1229, 13229, 1760, 9, 11735, 2156, 12442, 3148, 124, 5, 864, 9, 217, 812, 11, 5, 12429, 3207, 467, 36, 181, 3275, 4839, 454, 9633, 1437, 50118, 479, 959, 2156, 5, 414, 1542, 341, 30, 1368, 19911, 102, 7, 37357, 5, 181, 3275, 1663, 701, 1965, 16, 9, 4566, 773, 13, 1966, 9, 474, 575, 2122, 1663, 3926, 479, 1437, 50118, 71, 9311, 10, 346, 9, 801, 414, 1715, 2156, 1368, 19911, 102, 3919, 5, 32633, 1589, 414, 1915, 14948, 36, 32633, 1589, 13911, 4839, 1663, 801, 29, 414, 1542, 25, 5, 275, 414, 1300, 13, 29770, 5, 181, 3275, 1663, 701, 1965, 479, 1437, 50118, 5, 32633, 1589, 13911, 414, 1542, 16, 3924, 341, 30, 5, 1663, 539, 2156, 8, 24, 6308, 335, 15, 70, 538, 745, 1377, 11, 5, 247, 2156, 258, 92, 1663, 8, 35081, 2156, 14, 33, 10, 5635, 923, 9, 55, 87, 68, 564, 6, 151, 479, 1437, 50118, 5, 414, 32, 4786, 31, 745, 6687, 4088, 8, 97, 1715, 30, 10, 1546, 9, 112, 6, 1497, 882, 20719, 4189, 479, 1437, 50118, 5, 414, 2673, 15, 349, 695, 680, 5, 695, 1158, 1248, 2156, 1907, 9, 2122, 7, 28, 1490, 2156, 1355, 701, 2156, 3925, 4338, 7, 28, 11236, 2156, 8, 2259, 30, 343, 8, 2109, 479, 1437, 50118, 414, 32, 2867, 88, 5, 414, 1542, 71, 10, 1355, 34, 57, 1419, 8, 1663, 16, 7, 1642, 624, 1191, 360, 36, 752, 5124, 2156, 11735, 102, 4839, 479, 7, 3014, 12787, 19, 5, 181, 3275, 5007, 1965, 8, 7, 6925, 10, 5701, 3093, 9, 42561, 11, 18381, 21875, 2156, 1368, 19911, 102, 4689, 7, 15756, 5, 1663, 701, 1965, 23, 5, 672, 9, 20887, 17325, 911, 36, 43601, 281, 4839, 8, 92, 20407, 1245, 2109, 20887, 911, 36, 42179, 13738, 4839, 2156, 61, 32, 5, 6305, 9, 43601, 281, 11, 5, 92, 20407, 1245, 443, 36, 752, 5124, 2156, 11265, 4839, 479, 1437, 50118, 42, 2622, 10, 2559, 1965, 923, 13, 349, 9, 5, 35183, 43601, 281, 8, 42179, 13738, 2156, 25, 157, 25, 13, 5, 2929, 194, 3826, 911, 751, 475, 11146, 50, 42179, 1916, 10156, 479, 1437, 50118, 36, 634, 475, 11146, 50, 42179, 1916, 26613, 2156, 92, 11458, 8, 16448, 4636, 2946, 33, 117, 3826, 911, 479, 4839, 1437, 50118, 3249, 2156, 1368, 19911, 102, 1904, 7, 15756, 5, 1965, 634, 129, 474, 575, 2122, 1663, 414, 31, 32633, 1589, 13911, 479, 1437, 50118, 42, 414, 278, 1165, 4815, 2156, 12538, 2156, 1131, 4088, 2156, 8701, 8, 15380, 4575, 6342, 2644, 2156, 8, 97, 474, 1416, 3413, 479, 1437, 50118, 959, 2156, 13, 5, 601, 107, 9, 414, 577, 36, 6200, 111, 8162, 4839, 2156, 2491, 135, 9, 5, 414, 4590, 13, 43601, 281, 2156, 42179, 13738, 2156, 50, 3826, 911, 58, 5802, 479, 1437, 50118, 9, 5, 19671, 911, 2156, 8017, 56, 117, 431, 474, 575, 2122, 1663, 11, 23, 513, 361, 9, 5, 601, 107, 2156, 8, 316, 911, 56, 155, 50, 4163, 107, 9, 1663, 148, 5, 601, 12, 180, 675, 479, 7, 1877, 5, 6170, 9, 2623, 10, 5448, 7, 9824, 5, 9624, 21875, 14, 74, 898, 31, 29770, 5, 1965, 19, 215, 23581, 414, 11, 103, 911, 2156, 1368, 19911, 102, 1386, 21379, 5, 474, 575, 2122, 1663, 414, 19, 786, 111, 474, 575, 2156, 786, 111, 4860, 2156, 4107, 1663, 414, 31, 32633, 1589, 13911, 479, 1437, 50118, 42, 200, 278, 9, 414, 21, 802, 7, 28, 10, 5701, 16453, 13, 18381, 21875, 11, 5, 701, 9, 1098, 1663, 479, 1437, 50118, 24, 1165, 1304, 8, 8975, 2156, 29007, 45, 2164, 30, 4738, 2156, 18146, 8, 19773, 2156, 31567, 11925, 2156, 17867, 212, 27195, 2156, 343, 17236, 2156, 97, 168, 3413, 2156, 3960, 9, 13405, 2156, 8, 97, 3458, 3413, 479, 1437, 50118, 959, 2156, 29002, 5, 80, 3880, 9, 414, 396, 18624, 13, 5550, 11, 5, 3505, 8, 701, 9, 1663, 67, 4362, 4456, 36, 752, 5124, 2156, 11735, 428, 4839, 479, 1437, 50118, 77, 209, 80, 3880, 9, 414, 58, 2771, 2156, 70, 911, 56, 414, 2673, 13, 349, 76, 2156, 5, 746, 3149, 9, 2673, 1663, 1130, 31, 321, 4, 401, 7, 204, 4, 176, 325, 3925, 1730, 2156, 8, 5, 746, 701, 9, 1663, 11, 5, 414, 1542, 1130, 31, 68, 6791, 325, 7, 68, 21006, 325, 11, 5891, 11265, 1932, 479, 1437, 50118, 36, 25, 341, 11, 42, 1566, 2156, 1437, 3149, 1437, 839, 3925, 1730, 9, 1663, 2156, 8, 1437, 50118, 5, 181, 3275, 1663, 701, 1965, 21, 43547, 30, 29770, 41, 1013, 1965, 13, 349, 9, 5, 19671, 911, 36, 5, 1750, 9, 349, 443, 128, 29, 701, 228, 3925, 2767, 7, 5, 632, 674, 13, 5, 7091, 76, 4839, 8, 172, 11730, 10, 601, 12, 180, 1965, 13, 349, 443, 30, 2408, 154, 5, 601, 1013, 15271, 13, 349, 443, 30, 5, 3149, 9, 1663, 11, 349, 443, 13, 349, 76, 479, 143, 9, 5, 231, 6, 22814, 36, 19671, 1437, 601, 4839, 1437, 50118, 443, 3266, 13, 701, 228, 3925, 2767, 14, 13009, 130, 498, 50, 58, 540, 87, 65, 111, 371, 5, 632, 674, 13, 49, 7091, 76, 58, 15298, 25, 31187, 4733, 479, 1437, 50118, 13, 5, 1027, 1965, 2156, 129, 379, 107, 9, 414, 58, 341, 2156, 15002, 111, 8162, 2156, 1195, 87, 5, 455, 601, 107, 9, 414, 577, 2156, 142, 24, 21, 303, 14, 5, 132, 943, 107, 56, 818, 117, 913, 11, 617, 12964, 2787, 5, 1965, 31, 9624, 76, 111, 7, 111, 76, 21875, 36, 752, 5124, 2156, 11735, 428, 4839, 479, 1437, 50118, 5, 414, 341, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [ ]:
model.save_pretrained('bart_model')
tokenize.save_pretrained('bart_model')

/usr/local/lib/python3.12/dist-packages/transformers/modeling_utils.py:3922: UserWarning: Moving the following attributes in the config to the generation config: {'max_length': 142, 'min_length': 56, 'early_stopping': True, 'num_beams': 4, 'length_penalty': 2.0, 'no_repeat_ngram_size': 3, 'forced_bos_token_id': 0}. You are seeing this warning because you've set generation parameters in the model config, as opposed to in the generation config.
  warnings.warn(

('bart_model/tokenizer_config.json',
 'bart_model/special_tokens_map.json',
 'bart_model/vocab.json',
 'bart_model/merges.txt',
 'bart_model/added_tokens.json',
 'bart_model/tokenizer.json')

In [ ]:
from transformers import pipeline

In [ ]:
tokenizer = AutoTokenizer.from_pretrained('bart_model')
input_text = f"Summarize this medical report: {x}"  # Replace with your actual x
tokens = tokenize(input_text)

In [ ]:
print(f"Tokenized length: {len(tokens['input_ids'])}")  # If >1024, length is the problem
print(f"Max token ID: {max(tokens['input_ids'])}")
print(f"Tokenizer vocab size: {tokenizer.vocab_size}")

Tokenized length: 1481
Max token ID: 49329
Tokenizer vocab size: 50265

In [ ]:
summarizer = pipeline("summarization", model=model, tokenizer=tokenizer)  # Explicit device

Device set to use cpu

In [ ]:
x[0].split('.')

['background : the present study was carried out to assess the effects of community nutrition intervention based on advocacy approach on malnutrition status among school - aged children in shiraz , iran',
 'materials and methods : this case - control nutritional intervention has been done between 2008 and 2009 on 2897 primary and secondary school boys and girls ( 7 - 13 years old ) based on advocacy approach in shiraz , iran ',
 ' \n the project provided nutritious snacks in public schools over a 2-year period along with advocacy oriented actions in order to implement and promote nutritional intervention ',
 ' for evaluation of effectiveness of the intervention growth monitoring indices of pre- and post - intervention were statistically compared',
 'results:the frequency of subjects with body mass index lower than 5% decreased significantly after intervention among girls ( p = 0',
 '02 ) ',
 ' \n however , there were no significant changes among boys or total population ',
 ' \n the mean of all anthropometric indices changed significantly after intervention both among girls and boys as well as in total population ',
 " \n the pre- and post - test education assessment in both groups showed that the student 's average knowledge score has been significantly increased from 12",
 '5  3',
 '2 to 16',
 '8  4',
 '3 ( p < 0',
 '0001)',
 'conclusion : this study demonstrates the potential success and scalability of school feeding programs in iran ',
 ' \n community nutrition intervention based on the advocacy process model is effective on reducing the prevalence of underweight specifically among female school aged children ',
 '']

In [ ]:
text_summery=[]
for i in x[0].split('.'):
  input_text = f"Summarize this medical report: {i}"
  y = summarizer(input_text, max_length=30, min_length=10, do_sample=False)
  text_summery.append(y)

Your max_length is set to 30, but your input_length is only 12. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=6)
Your max_length is set to 30, but your input_length is only 25. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=12)
Your max_length is set to 30, but your input_length is only 12. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=6)
Your max_length is set to 30, but your input_length is only 12. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=6)
Your max_length is set to 30, but your input_length is only 12. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=6)
Your max_length is set to 30, but your input_length is only 14. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=7)
Your max_length is set to 30, but your input_length is only 12. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=6)
Your max_length is set to 30, but your input_length is only 28. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=14)
Your max_length is set to 30, but your input_length is only 10. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=5)

In [ ]:
text_summery

[[{'summary_text': 'Study was carried out to assess the effects of community nutrition intervention based on advocacy approach on malnutrition status among school - aged children in shir'}],
 [{'summary_text': 'This case - control nutritional intervention has been done between 2008 and 2009 on 2897 primary and secondary school boys and girls ( 7 - 13'}],
 [{'summary_text': 'The project provided nutritious snacks in public schools over a 2-year period.'}],
 [{'summary_text': 'Growth monitoring indices of pre- and post - intervention were statistically compared.'}],
 [{'summary_text': 'The frequency of subjects with body mass index lower than 5% decreased significantly after intervention among girls ( p = 0)'}],
 [{'summary_text': 'CNN.com will feature iReporter photos in a weekly Travel Snapshots gallery. Visit CNN.com/Travel each week for a'}],
 [{'summary_text': 'There were no significant changes among boys or total population.'}],
 [{'summary_text': 'The mean of all anthropometric indices changed significantly after intervention both among girls and boys as well as in total population.'}],
 [{'summary_text': "The student 's average knowledge score has been significantly increased from 12 to 14."}],
 [{'summary_text': 'CNN.com will feature iReporter photos in a weekly Travel Snapshots gallery. Visit CNN.com/Travel each week for a'}],
 [{'summary_text': 'CNN.com will feature iReporter photos in a weekly Travel Snapshots gallery. Visit CNN.com/Travel each week for a'}],
 [{'summary_text': 'CNN.com will feature iReporter photos in a weekly Travel Snapshots gallery. Visit CNN.com/Travel each week for a'}],
 [{'summary_text': 'CNN.com will feature iReporter photos in a weekly Travel Snapshots gallery. Visit CNN.com/Travel each week'}],
 [{'summary_text': 'CNN.com will feature iReporter photos in a weekly Travel Snapshots gallery. Visit CNN.com/Travel each week for a'}],
 [{'summary_text': 'This study demonstrates the potential success and scalability of school feeding programs in iran.'}],
 [{'summary_text': 'A community nutrition intervention based on the advocacy process model is effective on reducing the prevalence of underweight specifically among female school aged children.'}],
 [{'summary_text': 'CNN.com will feature iReporter photos in a weekly Travel Snapshots gallery. Visit CNN.com/Travel each week for a'}]]

In [ ]:
complete_text=' '.join(text[0]['summary_text'] for text in text_summery)

In [ ]:
input_text = f"Summarize this medical report: {complete_text}"
y = summarizer(input_text, max_length=200, min_length=50, do_sample=False)

In [ ]:
y

[{'summary_text': 'Study was carried out to assess the effects of community nutrition intervention based on advocacy approach on malnutrition status among school - aged children in shir. Project provided nutritious snacks in public schools over a 2-year period. Study demonstrates the potential success and scalability of school feeding programs in iran.'}]

In [ ]:
text_to_split=dataset['train']['article'][0]

In [ ]:
import re

re.split()

In [ ]:
import re
from transformers import AutoTokenizer  # Assume you have this for token counting

def recursive_chunk(text, max_tokens=512, overlap_ratio=0.2, tokenizer=tokenize):
    if tokenizer is None:
        tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")  # Or your model's tokenizer

    # Define separators in order of hierarchy: paragraphs > sentences > words
    separators = ['\n\n', '\n', '. ', ' ']  # Customize for your text (e.g., add section markers like '##')

    def split_with_hierarchy(current_text, sep_index=0):
        if sep_index >= len(separators):
            return [current_text]  # Base case: can't split further

        chunks = []
        parts = re.split(separators[sep_index], current_text)
        current_chunk = ""
        for part in parts:
            temp_chunk = current_chunk + (separators[sep_index] if current_chunk else "") + part
            token_count = len(tokenizer.encode(temp_chunk))
            if token_count > max_tokens:
                # If too big, recurse to finer separator
                sub_chunks = split_with_hierarchy(temp_chunk, sep_index + 1)
                chunks.extend(sub_chunks[:-1])  # Add all but last
                current_chunk = sub_chunks[-1]  # Carry over last sub-chunk
            else:
                current_chunk = temp_chunk

        if current_chunk:
            chunks.append(current_chunk)

        # Add overlap to chunks (except first)
        overlap_tokens = int(max_tokens * overlap_ratio)
        for i in range(1, len(chunks)):
            prev_tokens = tokenizer.encode(chunks[i-1])[-overlap_tokens:]
            overlap_text = tokenizer.decode(prev_tokens)
            chunks[i] = overlap_text + chunks[i]

        return chunks

    return split_with_hierarchy(text)

In [ ]:
chunk=recursive_chunk(text_to_split)

## project 4

In [ ]:
%pip install transformers datasets torch accelerate evaluate peft trl rouge_score

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.8.0+cu126)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.10.1)
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.17.1)
Collecting trl
  Downloading trl-0.24.0-py3-none-any.whl.metadata (11 kB)
Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.35.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.1.10)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.10.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (8.3.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (1.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.22.0)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 4.7 MB/s eta 0:00:00
Downloading trl-0.24.0-py3-none-any.whl (423 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 kB 5.3 MB/s eta 0:00:00
Building wheels for collected packages: rouge_score
  Building wheel for rouge_score (setup.py) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=1780252ec151076f333364325dc07ac7b3ec7823a927f4db223e546d13ada9d6
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge_score
Installing collected packages: rouge_score, trl, evaluate
Successfully installed evaluate-0.4.6 rouge_score-0.1.2 trl-0.24.0

In [ ]:
pip install -U bitsandbytes

Collecting bitsandbytes
  Downloading bitsandbytes-0.48.1-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.8.0+cu126)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (25.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Downloading bitsandbytes-0.48.1-py3-none-manylinux_2_24_x86_64.whl (60.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.1/60.1 MB 16.5 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.48.1

In [ ]:
from datasets import load_dataset
from peft import PromptTuningConfig,get_peft_model,PromptTuningInit, TaskType
from transformers import AutoTokenizer,AutoModelForSeq2SeqLM,Seq2SeqTrainer,Seq2SeqTrainingArguments
import torch
import evaluate

In [ ]:
dataset = load_dataset("gaussalgo/Canard_Wiki-augmented", split="train[:1000]")  # Use full for real
dataset = dataset.train_test_split(test_size=0.1)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [ ]:
dataset

DatasetDict({
    train: Dataset({
        features: ['History', 'QuAC_dialog_id', 'Question', 'Question_no', 'Rewrite', 'true_page_title', 'true_contexts', 'answer', 'true_contexts_wiki', 'extractive', 'retrieved_contexts'],
        num_rows: 900
    })
    test: Dataset({
        features: ['History', 'QuAC_dialog_id', 'Question', 'Question_no', 'Rewrite', 'true_page_title', 'true_contexts', 'answer', 'true_contexts_wiki', 'extractive', 'retrieved_contexts'],
        num_rows: 100
    })
})

In [ ]:
def text_generation(example):
  input_texts = []
  target_texts = []
  for i in range(len(example['History'])):
    hist = example['History'][i]
    '''if len(hist) != 0:
      hist_text = "\n".join(str(x) for x in hist)
    else:
      hist_text = 'NO HISTORY'''

    ques = example['Question'][i]

    input_texts.append(f"Rewrite query: {ques}")
    target_texts.append(example['Rewrite'][i])
  example['input_text'] = input_texts
  example['target_text'] = target_texts
  return example

In [ ]:
dataset_re=dataset.map(text_generation,batched=True,remove_columns=['History', 'QuAC_dialog_id', 'Question', 'Question_no', 'Rewrite', 'true_page_title', 'true_contexts', 'answer', 'true_contexts_wiki', 'extractive', 'retrieved_contexts'])

Map:   0%|          | 0/900 [00:00<?, ? examples/s]

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

In [ ]:
model_name = "t5-small"  # Or "t5-base" for better performance
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name,device_map='auto')

In [ ]:
def tokenize(example):
  model_inputs=tokenizer(example['input_text'],max_length=512,truncation=True,padding='max_length')
  labels=tokenizer(example['target_text'],max_length=512,truncation=True,padding='max_length')
  model_inputs['labels']=labels['input_ids']
  return model_inputs

In [ ]:
dataset_ready=dataset_re.map(tokenize,batched=True,remove_columns=['input_text','target_text'])

Map:   0%|          | 0/900 [00:00<?, ? examples/s]

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

In [ ]:
peft_config=PromptTuningConfig(
    task_type=TaskType.SEQ_2_SEQ_LM,
    prompt_tuning_init=PromptTuningInit.TEXT,  # Or RANDOM
    num_virtual_tokens=30,  # Soft prompt length
    prompt_tuning_init_text="Rewrite the query:",  # Optional init text
    tokenizer_name_or_path=model_name
)

In [ ]:
model=get_peft_model(model,peft_config)

In [ ]:
bleu=evaluate.load('bleu')

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
    result = bleu.compute(predictions=decoded_preds, references=[[l] for l in decoded_labels])
    return {"bleu": result["bleu"]}

In [ ]:
training_args = Seq2SeqTrainingArguments(
    output_dir="./p_tuned_query_rewriter",
    num_train_epochs=5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    #gradient_accumulation_steps=4,
    fp16=True,
    learning_rate=5e-4,  # Higher for prompts
    #weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="bleu",
    #report_to="none",
    #predict_with_generate=True
)

# Trainer
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset_ready["train"],
    eval_dataset=dataset_ready["test"],
    compute_metrics=compute_metrics
    #tokenizer=tokenizer
)

# Train and save
trainer.train()

The model is already on multiple devices. Skipping the move to device specified in `args`.
wandb: Currently logged in as: medicalassistance-ai (medicalassistance-ai-maai) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

In [ ]:
model.save_pretrained("./p_tuned_query_rewriter")
tokenizer.save_pretrained("./p_tuned_query_rewriter")

('./p_tuned_query_rewriter/tokenizer_config.json',
 './p_tuned_query_rewriter/special_tokens_map.json',
 './p_tuned_query_rewriter/spiece.model',
 './p_tuned_query_rewriter/added_tokens.json',
 './p_tuned_query_rewriter/tokenizer.json')

In [ ]:
input="when is it established?"
tokens=tokenizer(input,return_tensors='pt').to('cuda')

In [ ]:
from peft import PeftModelForCausalLM
from transformers import pipeline

In [ ]:
base_model=AutoModelForSeq2SeqLM.from_pretrained(model_name,device_map='auto')
peft_model=PeftModelForCausalLM.from_pretrained(base_model,'./p_tuned_query_rewriter')
rewiter=pipeline('text2text-generation',model=peft_model,tokenizer=tokenizer)
rewriter1=pipeline('text2text-generation',model=base_model,tokenizer=tokenizer)

Device set to use cuda:0
Device set to use cuda:0

In [ ]:
query = "when are you going to NY?"
rewritten = rewiter(f"Rewrite query: {query}", max_length=512)[0]["generated_text"]
print(rewritten)

Both `max_new_tokens` (=256) and `max_length`(=512) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

: when are you going to NY?

In [ ]:
rewiter(f"Rewrite query: {query}", max_length=512)

Both `max_new_tokens` (=256) and `max_length`(=512) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[{'generated_text': ': when are you going to NY?'}]

In [ ]:
# Importing classes and functions from the transformers library
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, Trainer, DataCollatorForLanguageModeling

# Importing the load_dataset function from the datasets library
from datasets import load_dataset

# Importing specific classes and functions from the peft library
from peft import get_peft_model, PromptTuningConfig, TaskType, PromptTuningInit, PeftModel, PeftConfig

# Importing the notebook_login function from the huggingface_hub library
from huggingface_hub import notebook_login

# Importing the os and time modules
import os
import time

In [ ]:
# Specify the pre-trained model name you want to use
model_name = "bigscience/bloomz-560m"

# Load the tokenizer associated with the pre-trained model
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load the pre-trained causal language model using the specified model name
foundation_model = AutoModelForCausalLM.from_pretrained(model_name,device_map='auto')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/222 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/14.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/715 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

In [ ]:
# Tokenize the input text using the specified tokenizer
input1 = tokenizer("Two things are infinite: ", return_tensors="pt", padding=True).to('cuda')

# Generate text using the pre-trained foundation model based on the provided input_ids and attention_mask.
foundation_outputs = foundation_model.generate(
    input_ids=input1["input_ids"],
    attention_mask=input1["attention_mask"],
    max_new_tokens=7,
    eos_token_id=tokenizer.eos_token_id
)

# Decode the generated token IDs into human-readable text.
decoded_output = tokenizer.batch_decode(foundation_outputs, skip_special_tokens=True)

# Print the decoded output, which represents the generated text.
print(decoded_output)

['Two things are infinite:  the number of people and the number']

In [ ]:
# Load the "english_quotes" dataset using the load_dataset function from the datasets library
data = load_dataset("Abirate/english_quotes")

# Tokenize the quotes in the dataset using the specified tokenizer
data = data.map(lambda samples: tokenizer(samples["quote"]).to('cuda'), batched=True)

# Select a subset of the training samples (first 50 samples in this case)
train_sample = data["train"].select(range(50))

# Display the selected subset of training samples
display(train_sample)

Dataset({
    features: ['quote', 'author', 'tags', 'input_ids', 'attention_mask'],
    num_rows: 50
})

In [ ]:
# Create a configuration for prompt tuning using the PromptTuningConfig class
peft_config = PromptTuningConfig(
    task_type=TaskType.CAUSAL_LM,
    prompt_tuning_init=PromptTuningInit.RANDOM,
    num_virtual_tokens=4,
    tokenizer_name_or_path=model_name
)

# Get a PeftModel using the specified foundation_model and prompt tuning configuration
peft_model = get_peft_model(foundation_model, peft_config)

# Print the trainable parameters of the PeftModel
print(peft_model.print_trainable_parameters())

trainable params: 4,096 || all params: 559,218,688 || trainable%: 0.0007
None

In [ ]:
%mkdir /content/working_dir

In [ ]:
# Define the output directory for storing Peft model outputs
output_directory = os.path.join("/content/working_dir", "peft_outputs")

# Create the working directory if it doesn't exist
if not os.path.exists("/content/working_dir"):
    os.mkdir("/content/working_dir")

# Create the output directory if it doesn't exist
if not os.path.exists(output_directory):
    os.mkdir(output_directory)

# Define training arguments for the Peft model
training_args = TrainingArguments(
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    output_dir=output_directory,  # Where the model predictions and checkpoints will be written
    no_cuda=True,  # This is necessary for CPU clusters.
    auto_find_batch_size=True,  # Find a suitable batch size that will fit into memory automatically
    learning_rate=3e-2,  # Higher learning rate than full fine-tuning
    num_train_epochs=5  # Number of passes to go through the entire fine-tuning dataset
)

/usr/local/lib/python3.12/dist-packages/transformers/training_args.py:1636: FutureWarning: using `no_cuda` is deprecated and will be removed in version 5.0 of 🤗 Transformers. Use `use_cpu` instead
  warnings.warn(

In [ ]:
# Enable gradient checkpointing in the Peft model's configuration
peft_model.config.gradient_checkpointing = True

# Create a Trainer instance for training the Peft model
trainer = Trainer(
    model=peft_model,  # We pass in the PEFT version of the foundation model, bloomz-560M
    args=training_args,  # Training arguments specifying output directory, GPU usage, batch size, etc.
    train_dataset=train_sample,  # Training dataset
    data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False)  # mlm=False indicates not to use masked language modeling
)

# Start the training process
trainer.train()

wandb: Currently logged in as: medicalassistance-ai (medicalassistance-ai-maai) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

In [ ]:
from datasets import load_dataset
from peft import PromptTuningConfig, get_peft_model, PromptTuningInit, TaskType
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    Seq2SeqTrainer,  # Use this for seq2seq specifics
    Seq2SeqTrainingArguments,  # Better for generation args
    DataCollatorForSeq2Seq,
    BitsAndBytesConfig
)
import evaluate
import torch
import os
import numpy as np

# Memory env
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
torch.cuda.empty_cache()

# Load dataset
dataset = load_dataset("gaussalgo/Canard_Wiki-augmented")

# Subset for quick testing (remove after debugging)
dataset = dataset.map(lambda x: x, remove_columns=dataset['train'].column_names)  # Placeholder
dataset['train'] = dataset['train'].select(range(1000))  # Test on 1000 samples
dataset['test'] = dataset['test'].select(range(200))     # Small eval

def text_generation(example):
    input_texts = []
    target_texts = []
    for i in range(len(example['Question'])):
        ques = example['Question'][i]
        input_texts.append(f"Rewrite query: {ques}")
        target_texts.append(example['Rewrite'][i])
    example['input_text'] = input_texts
    example['target_text'] = target_texts
    return example

dataset = dataset.map(text_generation, batched=True)

model_name = "t5-small"
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Quantization (keep for memory)
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)

model = AutoModelForSeq2SeqLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map='auto',
    torch_dtype=torch.float16
)

def tokenize(example):
    model_inputs = tokenizer(
        example['input_text'],
        max_length=256,
        truncation=True
    )
    labels = tokenizer(
        example['target_text'],
        max_length=128,
        truncation=True
    )
    model_inputs['labels'] = labels['input_ids']
    return model_inputs

tokenized_datasets = dataset.map(
    tokenize,
    batched=True,
    remove_columns=[col for col in dataset['train'].column_names if col not in ['input_ids', 'attention_mask', 'labels']]
)

# P-Tuning (use RANDOM to avoid text echo)
peft_config = PromptTuningConfig(
    task_type=TaskType.SEQ_2_SEQ_LM,
    prompt_tuning_init=PromptTuningInit.RANDOM,  # Less prone to repetition
    num_virtual_tokens=20,
    tokenizer_name_or_path=model_name
)
model = get_peft_model(model, peft_config)

# Metrics with error handling (filter invalid IDs)
bleu = evaluate.load('bleu')

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    # Replace -100 in labels (ignore index) with pad token ID
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)

    # Filter out invalid token IDs (e.g., <0 or >vocab_size)
    vocab_size = tokenizer.vocab_size
    predictions = [p for p in predictions if np.all((p >= 0) & (p < vocab_size))]
    labels = [l for l in labels if len(predictions) > 0]  # Align

    if len(predictions) == 0:
        return {"bleu": 0.0}  # Fallback

    try:
        decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
        decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
        result = bleu.compute(predictions=decoded_preds, references=[[l] for l in decoded_labels])
        return {"bleu": result["bleu"]}
    except Exception as e:
        print(f"Decode error: {e}")  # Log
        return {"bleu": 0.0}

# Data collator
data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model, padding=True)

# Seq2Seq-specific args (better for generation)
training_args = Seq2SeqTrainingArguments(
    output_dir="./p_tuned_query_rewriter",
    num_train_epochs=3,  # Start low for stability
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=8,
    fp16=True,
    learning_rate=3e-4,  # Even lower for early stability
    warmup_steps=300,  # Extended warmup
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="bleu",
    predict_with_generate=True,
    generation_max_length=128,
    gradient_checkpointing=True,
    dataloader_pin_memory=False,
    report_to="none",
    # Add gradient clipping to prevent exploding values
    max_grad_norm=1.0,
    # Predict on generation (not logits)
)

# Seq2SeqTrainer (use processing_class)
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    data_collator=data_collator,
    tokenizer=tokenizer,  # Or processing_class=tokenizer for future-proof
    compute_metrics=compute_metrics
)

# Train
trainer.train()
trainer.save_model("./fine_tuned_query_rewriter")
tokenizer.save_pretrained("./fine_tuned_query_rewriter")

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

Tokenized train columns: ['History', 'QuAC_dialog_id', 'Question', 'Question_no', 'Rewrite', 'true_page_title', 'true_contexts', 'answer', 'true_contexts_wiki', 'extractive', 'retrieved_contexts', 'input_text', 'target_text', 'input_ids', 'attention_mask', 'labels']
Sample shape: dict_keys(['History', 'QuAC_dialog_id', 'Question', 'Question_no', 'Rewrite', 'true_page_title', 'true_contexts', 'answer', 'true_contexts_wiki', 'extractive', 'retrieved_contexts', 'input_text', 'target_text', 'input_ids', 'attention_mask', 'labels'])

AttributeError: 'T5Config' object has no attribute 'generation_config'

In [ ]:
from datasets import load_dataset
from peft import PromptTuningConfig, get_peft_model, PromptTuningInit, TaskType
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    DataCollatorForSeq2Seq,
    BitsAndBytesConfig
)
import evaluate
import torch
import os
import numpy as np

# Memory env
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
torch.cuda.empty_cache()

# Load dataset
dataset = load_dataset("gaussalgo/Canard_Wiki-augmented")

# Subset for quick testing (before mapping; remove for full)
dataset["train"] = dataset["train"].select(range(1000))  # 1000 train samples
dataset["test"] = dataset["test"].select(range(200))     # 200 eval

# Remove unnecessary original columns before further processing
columns_to_remove = ['History', 'QuAC_dialog_id', 'Question_no', 'true_page_title', 'true_contexts', 'answer', 'true_contexts_wiki', 'extractive', 'retrieved_contexts']
dataset = dataset.remove_columns(columns_to_remove)


def text_generation(example):
    input_texts = []
    target_texts = []
    for i in range(len(example['Question'])):
        ques = example['Question'][i]
        input_texts.append(f"Rewrite query: {ques}")
        target_texts.append(example['Rewrite'][i])
    example['input_text'] = input_texts
    example['target_text'] = target_texts
    return example

# Format (keeps all columns for now, let remove_unused_columns handle)
dataset = dataset.map(text_generation, batched=True, remove_columns=['Question', 'Rewrite'])


model_name = "t5-small"
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Quantization config
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)

model = AutoModelForSeq2SeqLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map='auto',
    torch_dtype=torch.float16
)

def tokenize(example):
    # Tokenizer expects lists of strings when batched=True
    model_inputs = tokenizer(
        example['input_text'],
        max_length=256,
        truncation=True,
        padding=False  # No padding here – collator handles
    )
    labels = tokenizer(
        example['target_text'],
        max_length=128,
        truncation=True,
        padding=False
    )
    model_inputs['labels'] = labels['input_ids']
    return model_inputs

# Tokenize with batched=True
tokenized_datasets = dataset.map(tokenize, batched=True)

# Optional: Safe column filter (print to debug)
print("Tokenized train columns:", tokenized_datasets["train"].column_names)  # Should include input_ids, attention_mask, labels
print("Sample shape:", tokenized_datasets["train"][0].keys())

# Keep only essentials if needed (but avoid if causing empty)
# tokenized_datasets = tokenized_datasets.remove_columns([
#     col for col in tokenized_datasets["train"].column_names
#     if col not in ['input_ids', 'attention_mask', 'labels']
# ])

# P-Tuning (RANDOM to minimize echo)
peft_config = PromptTuningConfig(
    task_type=TaskType.SEQ_2_SEQ_LM,
    prompt_tuning_init=PromptTuningInit.RANDOM,
    num_virtual_tokens=20,
    tokenizer_name_or_path=model_name
)
model = get_peft_model(model, peft_config)

# Metrics with safeguards
bleu = evaluate.load('bleu')

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    # Handle -100 in labels
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)

    # Filter invalid IDs
    vocab_size = tokenizer.vocab_size
    valid_mask = np.all((predictions >= 0) & (predictions < vocab_size), axis=-1)
    predictions = predictions[valid_mask]
    labels = labels[valid_mask]

    if len(predictions) == 0:
        return {"bleu": 0.0}

    try:
        decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
        decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
        result = bleu.compute(predictions=decoded_preds, references=[[l] for l in decoded_labels])
        return {"bleu": result["bleu"]}
    except Exception as e:
        print(f"Metrics error: {e}")
        return {"bleu": 0.0}

# Data collator
data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model, padding=True)

# Seq2Seq-specific args (better for generation)
training_args = Seq2SeqTrainingArguments(
    output_dir="./p_tuned_query_rewriter",
    num_train_epochs=3,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=8,
    fp16=True,
    learning_rate=3e-4,
    warmup_steps=300,
    weight_decay=0.01,
    max_grad_norm=1.0,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="bleu",
    predict_with_generate=True,
    generation_max_length=128,
    generation_num_beams=4,
    gradient_checkpointing=True,
    dataloader_pin_memory=False,
    remove_unused_columns=False,
    report_to="none"
)

# Trainer (use processing_class to avoid warning)
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    data_collator=data_collator,
    tokenizer=tokenizer,  # Or processing_class=tokenizer for future-proof
    compute_metrics=compute_metrics
)

# Train and save
trainer.train()
trainer.save_model("./fine_tuned_query_rewriter")
tokenizer.save_pretrained("./fine_tuned_query_rewriter")

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

Tokenized train columns: ['History', 'QuAC_dialog_id', 'Question', 'Question_no', 'Rewrite', 'true_page_title', 'true_contexts', 'answer', 'true_contexts_wiki', 'extractive', 'retrieved_contexts', 'input_text', 'target_text', 'input_ids', 'attention_mask', 'labels']
Sample shape: dict_keys(['History', 'QuAC_dialog_id', 'Question', 'Question_no', 'Rewrite', 'true_page_title', 'true_contexts', 'answer', 'true_contexts_wiki', 'extractive', 'retrieved_contexts', 'input_text', 'target_text', 'input_ids', 'attention_mask', 'labels'])

/tmp/ipython-input-2844878837.py:153: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(

ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`History` in this case) have excessive nesting (inputs type `list` where type `int` is expected).

In [ ]:
peft_config = LoraConfig(
    r=16,  # Low rank
    lora_alpha=32,
    target_modules=['q_proj', 'v_proj'], # Add target_modules
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.CAUSAL_LM
)
trainer = SFTTrainer(
    model=model,
    train_dataset=dataset,
    #dataset_text_field="text",  # Points to your formatted text
    #max_seq_length=MAX_LENGTH,
    #tokenizer=tokenizer,
    args=SFTConfig(
    output_dir="./sft_output",
    num_train_epochs=2,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=8,
    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    warmup_ratio=0.05,
    logging_steps=10,
    save_strategy="epoch",
    #max_seq_length=1024,  # truncate long text
    #dataset_text_field="text",
    packing=True,        # True = multiple samples in one sequence
    bf16=True,
    fp16=False
)
    #packing=True,  # TRL bonus: packs multiple examples efficiently
)

In [ ]:
from datasets import load_dataset
from peft import LoraConfig, get_peft_model, PromptTuningInit, TaskType, prepare_model_for_kbit_training
from trl import SFTTrainer, SFTConfig  # 🔥 NEW IMPORTS
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig,Seq2SeqTrainingArguments,Seq2SeqTrainer, DataCollatorForLanguageModeling
import torch
import evaluate
import numpy as np
import os

# 🔥 OOM FIXES
#os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
torch.cuda.empty_cache()

# Dataset (SIMPLIFIED - just 'text' column)
dataset = load_dataset("gaussalgo/Canard_Wiki-augmented", split="train[:1000]")
dataset = dataset.train_test_split(test_size=0.1)

def text_generation(example):
    texts = []
    for i in range(len(example['History'])):
        hist = example['History'][i]
        hist_text = "\n".join(str(x) for x in hist) if len(hist) != 0 else 'NO HISTORY'
        ques = example['Question'][i]
        texts.append(f"Rewrite query: {ques}\nResponse: {example['Rewrite'][i]}")
    example['text'] = texts  # ← KEY: 'text' not 'input_text'
    return example

dataset_re = dataset.map(
    text_generation,
    batched=True,
    remove_columns=['History', 'QuAC_dialog_id', 'Question', 'Question_no', 'Rewrite', 'true_page_title', 'true_contexts', 'answer', 'true_contexts_wiki', 'extractive', 'retrieved_contexts']
)

# Explicitly remove all columns except 'text'
dataset_re = dataset_re.remove_columns([col for col in dataset_re['train'].column_names if col != 'text'])


# Model & Tokenizer
model_name = "LiquidAI/LFM2-350M-PII-Extract-JP"
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token

quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=quantization_config,
    device_map='auto'
)

# 🔥 NO TOKENIZE NEEDED! SFTTrainer handles it

# PEFT Config (unchanged)
peft_config = LoraConfig(
    r=16,  # Low rank
    lora_alpha=32,
    target_modules=['q_proj', 'v_proj'], # Add target_modules
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.CAUSAL_LM
)


model.config.use_cache = False
model = prepare_model_for_kbit_training(model)
model = get_peft_model(model, peft_config)

# 🔥 SFTConfig (Replaces TrainingArguments)
sft_config = SFTConfig(
    output_dir="./sft_output",
    num_train_epochs=2,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    #gradient_accumulation_steps=8,
    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    warmup_ratio=0.05,
    logging_steps=10,
    #save_strategy="epoch",
    #max_seq_length=1024,  # truncate long text
    #dataset_text_field="text",
    packing=True,        # True = multiple samples in one sequence
    bf16=True,
    fp16=False
)

# 🔥 BLEU Metrics (SAME)
bleu = evaluate.load('bleu')
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
    result = bleu.compute(predictions=decoded_preds, references=[l for l in decoded_labels])
    return {"bleu": result["bleu"]}
datacollector=DataCollatorForLanguageModeling(tokenizer, mlm=False)
# 🔥 SFTTrainer (Replaces Trainer)
sft_trainer = SFTTrainer(
    model=model,
    args=sft_config,
    train_dataset=dataset_re["train"],
    eval_dataset=dataset_re["test"],
    #tokenizer=tokenizer,
    compute_metrics=compute_metrics,
    peft_config=peft_config,
)

# 🔥 RUN - SIMPLER!
sft_trainer.train()
sft_trainer.save_model()

Map:   0%|          | 0/900 [00:00<?, ? examples/s]

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/peft/tuners/lora/bnb.py:348: UserWarning: Merge lora module to 4-bit linear may get different generations due to rounding errors.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:196: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
WARNING:trl.trainer.sft_trainer:Padding-free training is enabled, but the attention implementation is not set to a supported flash attention variant. Padding-free training flattens batches into a single sequence, and only the following implementations are known to reliably support this: flash_attention_2, flash_attention_3, kernels-community/flash-attn, kernels-community/flash-attn3, kernels-community/vllm-flash-attn3. Using other implementations may lead to unexpected behavior. To ensure compatibility, set `attn_implementation` in the model configuration to one of these supported options or verify that your attention mechanism can handle flattened sequences.
WARNING:trl.trainer.sft_trainer:You are using packing, but the attention implementation is not set to a supported flash attention variant. Packing gathers multiple samples into a single sequence, and only the following implementations are known to reliably support this: flash_attention_2, flash_attention_3, kernels-community/flash-attn, kernels-community/flash-attn3, kernels-community/vllm-flash-attn3. Using other implementations may lead to cross-contamination between samples. To avoid this, either disable packing by setting `packing=False`, or set `attn_implementation` in the model configuration to one of these supported options.

Adding EOS to train dataset:   0%|          | 0/900 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/900 [00:00<?, ? examples/s]

Packing train dataset:   0%|          | 0/900 [00:00<?, ? examples/s]

Adding EOS to eval dataset:   0%|          | 0/100 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/100 [00:00<?, ? examples/s]

Packing eval dataset:   0%|          | 0/100 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

TypeError: argument 'ids': 'list' object cannot be interpreted as an integer

In [ ]:
from datasets import load_dataset
from peft import PromptTuningConfig, get_peft_model, PromptTuningInit, TaskType, prepare_model_for_kbit_training
from transformers import AutoTokenizer, AutoModelForCausalLM, Seq2SeqTrainer, Seq2SeqTrainingArguments, BitsAndBytesConfig, DataCollatorForLanguageModeling
import torch
import evaluate
import numpy as np

# Load & prepare dataset
dataset = load_dataset("gaussalgo/Canard_Wiki-augmented", split="train[:1000]")
dataset = dataset.train_test_split(test_size=0.1)

def text_generation(example):
    input_texts = []
    for i in range(len(example['History'])):
        hist = example['History'][i]
        hist_text = "\n".join(str(x) for x in hist) if len(hist) != 0 else 'NO HISTORY'
        ques = example['Question'][i]
        # Full text: "Rewrite query: {ques} \nResponse: {rewrite}"
        input_texts.append(f"Rewrite query: {ques} \nResponse: {example['Rewrite'][i]}")
    example['input_text'] = input_texts
    return example

dataset_re = dataset.map(text_generation, batched=True, remove_columns=['History', 'QuAC_dialog_id', 'Question', 'Question_no', 'Rewrite', 'true_page_title', 'true_contexts', 'answer', 'true_contexts_wiki', 'extractive', 'retrieved_contexts'])

# FIXED TOKENIZER FUNCTION
def tokenize(example):
    model_inputs = tokenizer(
        example['input_text'],
        max_length=256,
        padding_side='left',
        truncation=True,
        padding='max_length'
    )
    # APPROACH 2: Copy input_ids to labels (full sequence loss)
    #model_inputs['labels'] = model_inputs['input_ids'].copy()
    return model_inputs

# Quantization & Model
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

model_name = "LiquidAI/LFM2-350M-PII-Extract-JP"
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token  # FIX: Set before model load
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=quantization_config,
    device_map='auto'
)

# Tokenize dataset
dataset_ready = dataset_re.map(
    tokenize,
    batched=True,
    remove_columns=['input_text']
)

# PEFT Config
peft_config = PromptTuningConfig(
    task_type=TaskType.CAUSAL_LM,
    prompt_tuning_init=PromptTuningInit.RANDOM,
    num_virtual_tokens=30,
    tokenizer_name_or_path=model_name
)

model.config.use_cache = False
model = prepare_model_for_kbit_training(model)
model = get_peft_model(model, peft_config)

# Metrics
bleu = evaluate.load('bleu')
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    # Replace -100 with pad_token_id (though none exist in Approach 2)
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
    decoded_preds = [pred.strip() for pred in decoded_preds]
    decoded_labels = [label.strip() for label in decoded_labels]
    result = bleu.compute(predictions=decoded_preds, references=[[l] for l in decoded_labels])
    return {"bleu": result["bleu"]}

# Training Args
training_args = Seq2SeqTrainingArguments(
    output_dir="./p_tuned_query_rewriter",
    num_train_epochs=5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    fp16=True,
    learning_rate=5e-4,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="bleu",
    predict_with_generate=True
)
datacollector=DataCollatorForLanguageModeling(tokenizer, mlm=False)

# Trainer
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset_ready["train"],
    eval_dataset=dataset_ready["test"],
    compute_metrics=compute_metrics,
    data_collator=datacollector
)

# TRAIN!
trainer.train()
trainer.save_model()

Map:   0%|          | 0/900 [00:00<?, ? examples/s]

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

Map:   0%|          | 0/900 [00:00<?, ? examples/s]

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

/usr/local/lib/python3.12/dist-packages/peft/peft_model.py:2066: UserWarning: Position ids are not supported for parameter efficient tuning. Ignoring position ids.
  warnings.warn("Position ids are not supported for parameter efficient tuning. Ignoring position ids.")
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

KeyboardInterrupt: